export type RootStackParamList = {
  Login: undefined;
  StudentDashboard: undefined;
  TeacherDashboard: undefined;
  TADashboard: undefined;
  AdminDashboard: undefined;
  Courses: undefined;
  Assignments: undefined;
  Quizzes: undefined;
  Progress: undefined;
  DiscussionForum: { courseId?: string };
  Messaging: undefined;
  LiveLectures: undefined;
  Videos: { courseId?: string };
  Resources: { courseId?: string };
  SupportTickets: undefined;
  Viva: undefined;
  Chatbot: undefined;
  Achievements: undefined;
  Leaderboard: undefined;
  Profile: undefined;
  CourseDetails: { offeringId: string };
  AssignmentDetails: { assignmentId: string };
  QuizTake: { quizId: string };
  LiveLectureRoom: { lectureId: string };
  VideoPlayer: { videoId: string };
  DiscussionThread: { threadId: string };
  SupportTicketDetails: { ticketId: string };
  VivaSession: { vivaId: string };
  ChatbotChat: undefined;
};